<?php

namespace Database\Seeders;

use App\Models\Hotel;
use Illuminate\Database\Seeder;

class HotelsTableSeeder extends Seeder
{
    public function run()
    {
        $hotels = [
            // Room only hotels
            [
                'name' => 'Kandy Hills Hotel',
                'description' => 'A comfortable hotel with great views of Kandy city. All rooms have private balconies, AC, and free WiFi. Located close to the Temple of the Tooth.',
                'full_description' => 'Nestled in the hills overlooking Kandy, our hotel offers breathtaking views of the city and surrounding mountains. Each of our 50 rooms features modern amenities including air conditioning, flat-screen TVs, and private balconies. Enjoy our rooftop infinity pool, full-service spa, and 24-hour room service. Perfect for both leisure and business travelers.',
                'image' => 'hotels/kh1.jpeg',
                'images' => json_encode([
        'hotels/kandy-hills/kh2.jpeg',
        'hotels/kandy-hills/kh3.jpeg',
        'hotels/kandy-hills/kh4.jpeg'
    ]),
                'type' => 'Room only',
                'category' => 'Family',
                'price_per_night' => 75.00,
                'food_options' => 'Breakfast buffet, À la carte dining, Room service, Vegan options',
                'has_nightlife' => true,
                'nightlife_description' => 'Rooftop cocktail bar with live music on weekends featuring local artists. Happy hour daily from 5-7pm.',
                'location' => 'Kandy',
                'phone' => '+94 812 345 678',
                'email' => 'reservations@kandyhillshotel.com',
                'rating' => '4-star',
                'has_wifi' => true,
                'has_pool' => true,
                'has_gym' => true,
                'has_spa' => true,
                'has_restaurant' => true,
                'meal_plan' => 'Breakfast included',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Colombo City Hotel',
                'description' => 'Modern hotel in the heart of Colombo with easy access to shopping and restaurants. Rooms feature contemporary decor and city views.',
                'full_description' => 'Located in Colombo\'s bustling business district, our 120-room property combines modern luxury with convenience. Enjoy floor-to-ceiling windows with panoramic city views, a state-of-the-art fitness center, and multiple dining options. Our executive lounge offers complimentary refreshments throughout the day. Just steps from major shopping and entertainment venues.',
                'image' => 'hotels/ch1.jpg',
                'images' => json_encode([
                    'hotels/colombo-city/ch2.jpeg',
                    'hotels/colombo-city/ch4.jpeg'
                ]),
                'type' => 'Room only',
                'category' => 'Business',
                'price_per_night' => 85.00,
                'food_options' => '24-hour room service, Coffee shop, Business lunch specials',
                'has_nightlife' => false,
                'nightlife_description' => null,
                'location' => 'Colombo',
                'phone' => '+94 112 345 678',
                'email' => 'info@colombocityhotel.com',
                'rating' => '4-star',
                'has_wifi' => true,
                'has_pool' => false,
                'has_gym' => true,
                'has_spa' => false,
                'has_restaurant' => true,
                'meal_plan' => 'Room only',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bed & Breakfast hotels
            [
                'name' => 'Beachfront B&B',
                'description' => 'Charming beachfront guesthouse with comfortable rooms and delicious breakfast included. Just steps from the sand in Unawatuna.',
                'full_description' => 'Our intimate 12-room beachfront property offers direct access to one of Sri Lanka\'s most beautiful beaches. Each room is uniquely decorated with local artwork and features private balconies or patios. Enjoy our famous breakfast buffet featuring tropical fruits and local specialties. Perfect for couples and small families looking for an authentic coastal experience.',
                'image' => 'hotels/b2jpg',
                'images' => json_encode(['hotels/beachfront-bb-1.jpg', 'hotels/beachfront-bb-2.jpg']),
                'type' => 'Bed & Breakfast',
                'category' => 'Honeymoon',
                'price_per_night' => 95.00,
                'food_options' => 'Full breakfast included, Seafood dinners available',
                'has_nightlife' => false,
                'nightlife_description' => null,
                'location' => 'Unawatuna',
                'phone' => '+94 912 345 678',
                'email' => 'stay@beachfrontbb.com',
                'rating' => '3-star',
                'has_wifi' => true,
                'has_pool' => false,
                'has_gym' => false,
                'has_spa' => false,
                'has_restaurant' => false,
                'meal_plan' => 'Bed & Breakfast',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Green Hills Guesthouse',
                'description' => 'Cozy guesthouse in Nuwara Eliya with beautiful garden views. Includes full English or Sri Lankan breakfast. Friendly staff can arrange tours.',
                'full_description' => 'Set amidst lush tea plantations, our colonial-style guesthouse offers 8 charming rooms with fireplaces and garden views. Start your day with our hearty breakfast featuring homemade jams and fresh-baked bread. Our knowledgeable staff can arrange tea plantation tours, hiking excursions, and visits to local waterfalls. Afternoon tea with homemade cakes is served daily in our garden lounge.',
                'image' => 'hotels/green-hills.jpg',
                'images' => json_encode(['hotels/green-hills-1.jpg', 'hotels/green-hills-2.jpg']),
                'type' => 'Bed & Breakfast',
                'category' => 'Family',
                'price_per_night' => 65.00,
                'food_options' => 'Breakfast included, Packed lunches available, Afternoon tea',
                'has_nightlife' => false,
                'nightlife_description' => null,
                'location' => 'Nuwara Eliya',
                'phone' => '+94 522 345 678',
                'email' => 'greetings@greenhillsguest.com',
                'rating' => '3-star',
                'has_wifi' => true,
                'has_pool' => false,
                'has_gym' => false,
                'has_spa' => false,
                'has_restaurant' => false,
                'meal_plan' => 'Bed & Breakfast',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Half Board hotels
            [
                'name' => 'Yala Safari Lodge',
                'description' => 'Comfortable lodge near Yala National Park. Half board package includes breakfast and dinner. Perfect base for safari adventures.',
                'full_description' => 'Our eco-friendly lodge offers 15 rustic-chic bungalows just minutes from Yala National Park\'s entrance. The half-board package includes a sunrise breakfast before your safari and a hearty dinner featuring local flavors. Our naturalist guides lead evening wildlife presentations. The property features a swimming pool shaped like a watering hole, perfect for cooling off after a day of adventure.',
                'image' => 'hotels/yala-lodge.jpg',
                'images' => json_encode(['hotels/yala-lodge-1.jpg', 'hotels/yala-lodge-2.jpg']),
                'type' => 'Half Board',
                'category' => 'Family',
                'price_per_night' => 120.00,
                'food_options' => 'Breakfast and dinner included, Packed lunches available',
                'has_nightlife' => false,
                'nightlife_description' => null,
                'location' => 'Yala',
                'phone' => '+94 472 345 678',
                'email' => 'bookings@yalalodge.com',
                'rating' => '4-star',
                'has_wifi' => true,
                'has_pool' => true,
                'has_gym' => false,
                'has_spa' => false,
                'has_restaurant' => true,
                'meal_plan' => 'Half Board',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cultural Resort',
                'description' => 'Beautiful resort with traditional architecture near Sigiriya. Half board includes breakfast and dinner with local cuisine options.',
                'full_description' => 'Inspired by ancient Sri Lankan architecture, our resort features 40 villas with private courtyards and outdoor showers. The half-board plan includes a lavish breakfast buffet and themed dinner nights showcasing regional specialties. Participate in cooking classes, traditional dance performances, and artisan workshops. The infinity pool offers stunning views of Sigiriya Rock.',
                'image' => 'hotels/cultural-resort.jpg',
                'images' => json_encode(['hotels/cultural-resort-1.jpg', 'hotels/cultural-resort-2.jpg']),
                'type' => 'Half Board',
                'category' => 'Honeymoon',
                'price_per_night' => 150.00,
                'food_options' => 'Breakfast and dinner included, Cooking classes available',
                'has_nightlife' => true,
                'nightlife_description' => 'Traditional dance performances three times weekly, Cultural shows with local musicians',
                'location' => 'Sigiriya',
                'phone' => '+94 662 345 678',
                'email' => 'experience@culturalresort.com',
                'rating' => '4-star',
                'has_wifi' => true,
                'has_pool' => true,
                'has_gym' => false,
                'has_spa' => true,
                'has_restaurant' => true,
                'meal_plan' => 'Half Board',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // All Inclusive hotels
            [
                'name' => 'Paradise Beach Resort',
                'description' => 'Luxury all-inclusive beach resort with pools, spa, and multiple restaurants. Includes all meals, drinks, and many activities.',
                'full_description' => 'Our 5-star all-inclusive resort spans 20 acres of pristine beachfront. Enjoy unlimited dining at 6 specialty restaurants, 24-hour room service, and premium beverages. Activities include water sports, yoga classes, and nightly entertainment. The spa features Ayurvedic treatments and a hydrotherapy circuit. Perfect for those seeking a worry-free luxury vacation.',
                'image' => 'hotels/paradise-beach.jpg',
                'images' => json_encode(['hotels/paradise-beach-1.jpg', 'hotels/paradise-beach-2.jpg']),
                'type' => 'All Inclusive',
                'category' => 'Honeymoon',
                'price_per_night' => 250.00,
                'food_options' => 'All meals included, 24-hour snacks, Premium beverages',
                'has_nightlife' => true,
                'nightlife_description' => 'Nightly entertainment including live bands, DJ parties twice weekly, Beach bonfires',
                'location' => 'Bentota',
                'phone' => '+94 342 345 678',
                'email' => 'reservations@paradisebeach.com',
                'rating' => '5-star',
                'has_wifi' => true,
                'has_pool' => true,
                'has_gym' => true,
                'has_spa' => true,
                'has_restaurant' => true,
                'meal_plan' => 'All Inclusive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Family Fun Resort',
                'description' => 'All-inclusive family resort with kids club, water slides, and daily entertainment. All meals, snacks, and non-alcoholic drinks included.',
                'full_description' => 'Designed specifically for families, our resort features a water park with slides, a kids club with supervised activities, and family-friendly entertainment. The all-inclusive package covers all meals at 4 themed restaurants, ice cream parlors, and unlimited non-alcoholic drinks. Parents can enjoy the adults-only pool area while kids are entertained by our staff.',
                'image' => 'hotels/family-fun.jpg',
                'images' => json_encode(['hotels/family-fun-1.jpg', 'hotels/family-fun-2.jpg']),
                'type' => 'All Inclusive',
                'category' => 'Family',
                'price_per_night' => 220.00,
                'food_options' => 'All meals included, Kids menu available, Ice cream station',
                'has_nightlife' => true,
                'nightlife_description' => 'Family-friendly evening shows, Movie nights under the stars, Teen disco',
                'location' => 'Negombo',
                'phone' => '+94 312 345 678',
                'email' => 'fun@familyresort.com',
                'rating' => '4-star',
                'has_wifi' => true,
                'has_pool' => true,
                'has_gym' => true,
                'has_spa' => true,
                'has_restaurant' => true,
                'meal_plan' => 'All Inclusive',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Business hotels
            [
                'name' => 'Colombo Business Hotel',
                'description' => 'Modern hotel with business center, meeting rooms, and executive lounge. Conveniently located in Colombo\'s business district.',
                'full_description' => 'Designed for business travelers, our hotel offers soundproof rooms with workstations, a 24-hour business center, and 10 meeting rooms of various sizes. The executive lounge provides complimentary breakfast, evening cocktails, and private check-in. Located within walking distance of Colombo\'s financial institutions and government offices.',
                'image' => 'hotels/colombo-business.jpg',
                'images' => json_encode(['hotels/colombo-business-1.jpg', 'hotels/colombo-business-2.jpg']),
                'type' => 'Room only',
                'category' => 'Business',
                'price_per_night' => 110.00,
                'food_options' => 'Executive lounge access, 24-hour room service, Coffee bar',
                'has_nightlife' => false,
                'nightlife_description' => null,
                'location' => 'Colombo',
                'phone' => '+94 112 987 654',
                'email' => 'corporate@colombobusiness.com',
                'rating' => '4-star',
                'has_wifi' => true,
                'has_pool' => false,
                'has_gym' => true,
                'has_spa' => false,
                'has_restaurant' => true,
                'meal_plan' => 'Room only',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'City Suites',
                'description' => 'Luxury serviced apartments with full business facilities. Ideal for extended business stays with kitchenettes and laundry service.',
                'full_description' => 'Our all-suite property offers spacious accommodations ranging from studios to two-bedroom apartments, each with fully equipped kitchenettes and separate living areas. Business amenities include in-room workstations, complimentary high-speed internet, and access to our business lounge with printing facilities. Weekly housekeeping and grocery delivery services available.',
                'image' => 'hotels/city-suites.jpg',
                'images' => json_encode(['hotels/city-suites-1.jpg', 'hotels/city-suites-2.jpg']),
                'type' => 'Room only',
                'category' => 'Business',
                'price_per_night' => 130.00,
                'food_options' => 'Kitchenettes in all rooms, Grocery delivery available, Breakfast cafe',
                'has_nightlife' => false,
                'nightlife_description' => null,
                'location' => 'Colombo',
                'phone' => '+94 112 876 543',
                'email' => 'reservations@citysuites.com',
                'rating' => '4-star',
                'has_wifi' => true,
                'has_pool' => false,
                'has_gym' => true,
                'has_spa' => false,
                'has_restaurant' => false,
                'meal_plan' => 'Room only',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Honeymoon hotels
            [
                'name' => 'Romantic Beach Villas',
                'description' => 'Private beachfront villas with plunge pools and butler service. Special honeymoon packages available with romantic dinners.',
                'full_description' => 'Our 12 exclusive villas each feature private plunge pools, outdoor showers, and direct beach access. Honeymoon packages include romantic turndown service, a private beach dinner, and couples spa treatments. The resort is adults-only, ensuring a peaceful atmosphere. Enjoy complimentary sunset cocktails and personalized butler service throughout your stay.',
                'image' => 'hotels/romantic-villas.jpg',
                'images' => json_encode(['hotels/romantic-villas-1.jpg', 'hotels/romantic-villas-2.jpg']),
                'type' => 'All Inclusive',
                'category' => 'Honeymoon',
                'price_per_night' => 350.00,
                'food_options' => 'All meals included, Private dining options, Premium champagne',
                'has_nightlife' => false,
                'nightlife_description' => null,
                'location' => 'Tangalle',
                'phone' => '+94 472 987 654',
                'email' => 'romance@beachvillas.com',
                'rating' => '5-star',
                'has_wifi' => true,
                'has_pool' => true,
                'has_gym' => false,
                'has_spa' => true,
                'has_restaurant' => true,
                'meal_plan' => 'All Inclusive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hill Country Retreat',
                'description' => 'Luxury boutique hotel with stunning mountain views. Honeymoon suites feature private balconies and jacuzzis.',
                'full_description' => 'Perched on a hillside with panoramic views of tea plantations, our intimate 10-room property offers unparalleled privacy and luxury. Honeymoon suites include four-poster beds, deep soaking tubs, and private jacuzzis on the balcony. Enjoy private guided hikes, afternoon tea service in your room, and in-room couples massages. The restaurant features farm-to-table cuisine with ingredients sourced from local organic farms.',
                'image' => 'hotels/hill-retreat.jpg',
                'images' => json_encode(['hotels/hill-retreat-1.jpg', 'hotels/hill-retreat-2.jpg']),
                'type' => 'Bed & Breakfast',
                'category' => 'Honeymoon',
                'price_per_night' => 280.00,
                'food_options' => 'Breakfast included, Gourmet dinners available, Afternoon tea',
                'has_nightlife' => false,
                'nightlife_description' => null,
                'location' => 'Ella',
                'phone' => '+94 572 345 678',
                'email' => 'escape@hillretreat.com',
                'rating' => '5-star',
                'has_wifi' => true,
                'has_pool' => true,
                'has_gym' => false,
                'has_spa' => true,
                'has_restaurant' => true,
                'meal_plan' => 'Bed & Breakfast',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Hotel::insert($hotels);
    }
}