<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class VehiclesTableSeeder extends Seeder
{
    public function run()
    {
        // Create vehicles directory if it doesn't exist
        if (!Storage::exists('public/vehicles')) {
            Storage::makeDirectory('public/vehicles');
        }

        $vehicles = [
            // Cars - Economy
            [
                'name' => 'Toyota Prius (2019)',
                'description' => 'Fuel-efficient hybrid for Colombo city driving',
                'full_description' => 'Imported from Japan, this Prius has excellent fuel economy (30km/L) perfect for Sri Lankan roads. Includes English navigation system.',
                'images' => ['vehicles/prians.jpg', 'vehicles/prias2.jpg'],
                'type' => 'Car',
                'category' => 'Economy',
                'price_per_day' => 6000,
                'capacity' => 4,
                'transmission' => 'Automatic',
                'fuel_type' => 'Hybrid',
                'air_conditioned' => true,
                'doors' => 4,
                'bags' => 2,
                'color' => 'Silver',
                'year' => 2019,
                'plate_number' => 'CAB-8734',
                'features' => ['Bluetooth', 'Reverse Camera', 'Keyless Entry', 'ECO Mode'],
                'available' => true,
                'location' => 'Colombo Fort',
            ],
            [
                'name' => 'Perodua Axia (2020)',
                'description' => 'Compact budget car perfect for narrow roads',
                'full_description' => 'Malaysian-made Axia with excellent fuel efficiency (20km/L). Compact size makes it ideal for Sri Lankan roads and parking.',
                'images' => ['vehicles/a1.jpg', 'vehicles/a1.jpg'],
                'type' => 'Car',
                'category' => 'Budget',
                'price_per_day' => 4500,
                'capacity' => 4,
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'air_conditioned' => true,
                'doors' => 4,
                'bags' => 1,
                'color' => 'Red',
                'year' => 2020,
                'plate_number' => 'CAX-4532',
                'features' => ['Power Steering', 'CD Player', 'Central Locking'],
                'available' => true,
                'location' => 'Kandy',
            ],

            // Cars - Standard
            [
                'name' => 'Toyota Allion (2018)',
                'description' => 'Popular Sri Lankan sedan with comfort',
                'full_description' => 'Japanese used Allion with 1500cc engine. Popular choice for Sri Lankan families with comfortable ride quality.',
                'images' => ['vehicles/allion.jpg', 'vehicles/allion-2.jpg'],
                'type' => 'Car',
                'category' => 'Standard',
                'price_per_day' => 7500,
                'capacity' => 5,
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'air_conditioned' => true,
                'doors' => 4,
                'bags' => 3,
                'color' => 'White',
                'year' => 2018,
                'plate_number' => 'CAR-9821',
                'features' => ['Push Start', 'Auto AC', 'Alloy Wheels', 'Smart Key'],
                'available' => true,
                'location' => 'Negombo',
            ],
            [
                'name' => 'Honda Vezel (2017)',
                'description' => 'Hybrid crossover popular in Sri Lanka',
                'full_description' => 'Japanese used hybrid SUV with excellent resale value. 1500cc engine with hybrid system gives good fuel economy.',
                'images' => ['vehicles/vezel.jpg', 'vehicles/vezel-2.jpg'],
                'type' => 'Car',
                'category' => 'Standard',
                'price_per_day' => 8000,
                'capacity' => 5,
                'transmission' => 'Automatic',
                'fuel_type' => 'Hybrid',
                'air_conditioned' => true,
                'doors' => 4,
                'bags' => 3,
                'color' => 'Blue',
                'year' => 2017,
                'plate_number' => 'CAS-7623',
                'features' => ['Sunroof', 'Lane Watch', 'ECO Mode', 'Touchscreen'],
                'available' => true,
                'location' => 'Galle',
            ],

            // SUVs
            [
                'name' => 'Toyota Land Cruiser Prado (2016)',
                'description' => 'Luxury SUV for Sri Lankan terrain',
                'full_description' => 'Diesel 3000cc engine with full options. Perfect for Sri Lankan roads with 4WD capability for rural areas.',
                'images' => ['vehicles/prado.jpg', 'vehicles/prado-2.jpg'],
                'type' => 'SUV',
                'category' => 'Luxury',
                'price_per_day' => 25000,
                'capacity' => 7,
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'air_conditioned' => true,
                'doors' => 5,
                'bags' => 5,
                'color' => 'White',
                'year' => 2016,
                'plate_number' => 'CAQ-4598',
                'features' => ['4WD', 'Leather Seats', 'Third Row', 'Navigation'],
                'available' => true,
                'location' => 'Colombo',
            ],
            [
                'name' => 'Mitsubishi Montero Sport (2019)',
                'description' => 'Affordable SUV for Sri Lankan families',
                'full_description' => '2500cc diesel engine with good ground clearance. Popular choice for Sri Lankan roads and occasional off-road use.',
                'images' => ['vehicles/montero.jpg', 'vehicles/montero-2.jpg'],
                'type' => 'SUV',
                'category' => 'Standard',
                'price_per_day' => 12000,
                'capacity' => 7,
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'air_conditioned' => true,
                'doors' => 5,
                'bags' => 4,
                'color' => 'Black',
                'year' => 2019,
                'plate_number' => 'CAP-3421',
                'features' => ['4WD', 'Roof Rails', 'Fog Lights', 'Rear AC'],
                'available' => true,
                'location' => 'Kandy',
            ],

            // Vans
            [
                'name' => 'Toyota Hiace Super GL (2015)',
                'description' => 'Comfortable van for Sri Lankan groups',
                'full_description' => '3000cc diesel engine with comfortable seating. Popular for airport transfers and family trips in Sri Lanka.',
                'images' => ['vehicles/hiace.jpg', 'vehicles/hiace-2.jpg'],
                'type' => 'Van',
                'category' => 'People Carrier',
                'price_per_day' => 15000,
                'capacity' => 12,
                'transmission' => 'Manual',
                'fuel_type' => 'Diesel',
                'air_conditioned' => true,
                'doors' => 3,
                'bags' => 8,
                'color' => 'White',
                'year' => 2015,
                'plate_number' => 'CAV-9832',
                'features' => ['Rear AC', 'Privacy Glass', 'Step Board', 'Overhead Storage'],
                'available' => true,
                'location' => 'Colombo Airport',
            ],
            [
                'name' => 'Nissan Caravan (2018)',
                'description' => 'Spacious van for Sri Lankan tours',
                'full_description' => 'High roof van perfect for tall passengers. Often used for Sri Lanka tour packages with luggage space.',
                'images' => ['vehicles/caravan.jpg', 'vehicles/caravan-2.jpg'],
                'type' => 'Van',
                'category' => 'People Carrier',
                'price_per_day' => 13000,
                'capacity' => 9,
                'transmission' => 'Manual',
                'fuel_type' => 'Diesel',
                'air_conditioned' => true,
                'doors' => 3,
                'bags' => 6,
                'color' => 'Silver',
                'year' => 2018,
                'plate_number' => 'CAV-6723',
                'features' => ['High Roof', 'Sliding Doors', 'Rear AC', 'Step Board'],
                'available' => true,
                'location' => 'Negombo',
            ],

            // Luxury Vehicles
            [
                'name' => 'Mercedes-Benz E200 (2020)',
                'description' => 'Luxury sedan for business in Sri Lanka',
                'full_description' => 'Brand new condition with AMG package. Perfect for business meetings and special occasions in Sri Lanka.',
                'images' => ['vehicles/mercedes.jpg', 'vehicles/mercedes-2.jpg'],
                'type' => 'Car',
                'category' => 'Luxury',
                'price_per_day' => 35000,
                'capacity' => 4,
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'air_conditioned' => true,
                'doors' => 4,
                'bags' => 3,
                'color' => 'Black',
                'year' => 2020,
                'plate_number' => 'CAL-0012',
                'features' => ['Leather Seats', 'Panoramic Roof', 'Ambient Lighting', 'Premium Sound'],
                'available' => true,
                'location' => 'Colombo 7',
            ],
            [
                'name' => 'Range Rover Vogue (2019)',
                'description' => 'Ultimate luxury SUV for Sri Lanka',
                'full_description' => '3000cc diesel with all options. Air suspension provides comfortable ride on Sri Lankan roads.',
                'images' => ['vehicles/range.jpg', 'vehicles/range-2.jpg'],
                'type' => 'SUV',
                'category' => 'Luxury',
                'price_per_day' => 45000,
                'capacity' => 5,
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'air_conditioned' => true,
                'doors' => 5,
                'bags' => 4,
                'color' => 'White',
                'year' => 2019,
                'plate_number' => 'CAL-0007',
                'features' => ['4WD', 'Air Suspension', 'Heated Seats', '360 Camera'],
                'available' => true,
                'location' => 'Colombo 3',
            ],

            // Bikes
            [
                'name' => 'Royal Enfield Classic 350 (2021)',
                'description' => 'Heritage bike for Sri Lankan roads',
                'full_description' => 'Perfect for scenic rides along Sri Lankan coasts and hill country. Includes helmet and basic rain gear.',
                'images' => ['vehicles/enfield.jpg', 'vehicles/enfield-2.jpg'],
                'type' => 'Bike',
                'category' => 'Cruiser',
                'price_per_day' => 4000,
                'capacity' => 2,
                'transmission' => 'Manual',
                'fuel_type' => 'Petrol',
                'air_conditioned' => false,
                'doors' => 0,
                'bags' => 0,
                'color' => 'Black',
                'year' => 2021,
                'plate_number' => 'MB-8732',
                'features' => ['Retro Style', 'Comfort Seat', 'Alloy Wheels'],
                'available' => true,
                'location' => 'Mirissa',
            ],
            [
                'name' => 'Honda Dio (2022)',
                'description' => 'Automatic scooter for Sri Lankan cities',
                'full_description' => 'Fuel efficient automatic scooter perfect for getting around Sri Lankan cities and beaches. Includes helmet.',
                'images' => ['vehicles/dio.jpg', 'vehicles/dio-2.jpg'],
                'type' => 'Bike',
                'category' => 'Scooter',
                'price_per_day' => 2000,
                'capacity' => 2,
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'air_conditioned' => false,
                'doors' => 0,
                'bags' => 0,
                'color' => 'Red',
                'year' => 2022,
                'plate_number' => 'MB-3421',
                'features' => ['Automatic', 'Under Seat Storage', 'Fuel Gauge'],
                'available' => true,
                'location' => 'Unawatuna',
            ],
        ];

        foreach ($vehicles as $vehicleData) {
            Vehicle::create($vehicleData);
        }

        $this->command->info('Successfully seeded 12 Sri Lankan vehicles!');
    }
}